"""Stable phase-one domain contracts."""

from market_data_center.domain.calendar import calculate_trading_day_links
from market_data_center.domain.capital import (
    CapitalFinding,
    CapitalValidationResult,
    capital_natural_key,
    capital_natural_key_json,
    validate_capital,
)
from market_data_center.domain.classification import (
    ClassificationCatalogSnapshotRecord,
    ClassificationDefinition,
    ClassificationFinding,
    ClassificationMemberSnapshotRecord,
    ClassificationRecord,
    ClassificationType,
    validate_catalog,
    validate_member_snapshot,
)
from market_data_center.domain.entities import CalculatedTradingDay, SecurityNameHistory
from market_data_center.domain.ingestion import (
    DatasetCode,
    IngestionRun,
    IngestionStatus,
    ProviderCode,
    QualityResult,
    QualitySeverity,
    QualityStatus,
    RawFileFormat,
    RawManifest,
)
from market_data_center.domain.records import (
    CapitalRecord,
    CorporateActionStatus,
    DailyBarRecord,
    DistributionRecord,
    Exchange,
    IngestionEnvelope,
    Market,
    RightsIssueRecord,
    SecurityRecord,
    SecurityStatus,
    SecurityType,
    ShareCapitalRecord,
    TradeStatus,
    TradingDayRecord,
)
from market_data_center.domain.validation import (
    ValidationFinding,
    ValidationRule,
    validate_daily_bars,
)

__all__ = [
    "CalculatedTradingDay",
    "CapitalFinding",
    "CapitalRecord",
    "CapitalValidationResult",
    "ClassificationCatalogSnapshotRecord",
    "ClassificationDefinition",
    "ClassificationFinding",
    "ClassificationMemberSnapshotRecord",
    "ClassificationRecord",
    "ClassificationType",
    "CorporateActionStatus",
    "DailyBarRecord",
    "DatasetCode",
    "DistributionRecord",
    "Exchange",
    "IngestionEnvelope",
    "IngestionRun",
    "IngestionStatus",
    "Market",
    "ProviderCode",
    "QualityResult",
    "QualitySeverity",
    "QualityStatus",
    "RawFileFormat",
    "RawManifest",
    "RightsIssueRecord",
    "SecurityNameHistory",
    "SecurityRecord",
    "SecurityStatus",
    "SecurityType",
    "ShareCapitalRecord",
    "TradeStatus",
    "TradingDayRecord",
    "ValidationFinding",
    "ValidationRule",
    "calculate_trading_day_links",
    "capital_natural_key",
    "capital_natural_key_json",
    "validate_capital",
    "validate_catalog",
    "validate_daily_bars",
    "validate_member_snapshot",
]
